### ISSUE TITLE
您的黑苹果完美吗

### ISSUE THREAD

**Issue by ghost** [zenuo/thinkpad-x280-hackintosh#1]
我也是ThinkPad x280，还没有用你的efi试。之前我试的一个老外的efi，电池电量获取不到，触摸板可用，但是无法设置。

**Comment by zenuo** [comment]
你好，目前的版本也无法识别电池、无法设置触控板😂

--------原始邮件--------
在 2020年1月2日 上午1:31, Aimai Hu 来信：

**Comment by jcheunglin** [comment]
摄像头能驱动吗

**Comment by zenuo** [comment]
> 摄像头能驱动吗

目前是可以的

**Comment by jcheunglin** [comment]
请问你的摄像头带不带红外啊，也就是面部识别

**Comment by zenuo** [comment]
> 请问你的摄像头带不带红外啊，也就是面部识别

不带的哈

**Comment by zenuo** [comment]
Close due to lack of activity.

**Comment by ghost** [comment]
哈哈，我来通报一声，用这个基本完美：https://github.com/EETagent/T480-OpenCore-Hackintosh

**Comment by zenuo** [comment]
> 哈哈，我来通报一声，用这个基本完美：https://github.com/EETagent/T480-OpenCore-Hackintosh

👌thanks
